version: 2
updates:
  - package-ecosystem: "npm"
    cooldown:
      default-days: 1
      exclude: ['neuro-game-sdk']
    directory: "/"
    schedule:
      interval: "weekly"
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - dependabot
      - javascript
      - meta
    ignore:
      - dependency-name: "@types/vscode" # Manually bump with the VS Code engine version
      - dependency-name: "@types/json-schema"
      - dependency-name: "@types/node" # Manually bump with the VS Code engine version
    open-pull-requests-limit: 3
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
      prod-dependencies:
        applies-to: version-updates
        dependency-type: production
        update-types:
          - minor
          - patch
      security:
        applies-to: security-updates
        dependency-type: production
      security-dev:
        applies-to: security-updates
        dependency-type: development
  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 2
    directory: /
    schedule:
      interval: monthly
      time: "00:00"
      timezone: "Etc/UTC"
    labels:
      - dependabot
      - github_actions
      - meta
