onlyBuiltDependencies:
  - '@playwright/browser-chromium'
  - '@vscode/vsce-sign'
  - esbuild
  - keytar
overrides:
  diff@>=6.0.0 <8.0.3: '~8.0.3'
  js-yaml@>=4.0.0 <4.1.1: '~4.1.1'
  serialize-javascript@<7.0.5: '~7.0.5'
