allowBuilds:
  '@playwright/browser-chromium': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
minimumReleaseAgeExclude:
  - neuro-game-sdk@1.1.1
overrides:
  diff@>=6.0.0 <8.0.3: '~8.0.3'
  js-yaml@>=4.0.0 <4.1.1: '~4.1.1'
  serialize-javascript@<7.0.5: '~7.0.5'
