name: Quick checks

on:
    push:
    pull_request:

permissions: {}

jobs:
    type-check:
      name: Type checker
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v6
          with:
            persist-credentials: false
        
        - name: Setup pnpm
          uses: pnpm/action-setup@v6
        
        - name: Setup Node.js
          uses: actions/setup-node@v6
          with:
            node-version-file: ./package.json
            cache: 'pnpm'
            cache-dependency-path: './pnpm-lock.yaml'
        
        - name: clean-install deps
          run: pnpm install --frozen-lockfile

        - name: type check
          run: pnpm types

    lint-check:
      name: Lint checker
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v6
            with:
              persist-credentials: false

          - name: Setup pnpm
            uses: pnpm/action-setup@v6

          - name: Setup Node.js
            uses: actions/setup-node@v6
            with:
              node-version-file: ./package.json
              cache: 'pnpm'
              cache-dependency-path: './pnpm-lock.yaml'

          - name: clean-install deps
            run: pnpm install --frozen-lockfile

          - name: lint check
            run: pnpm eslint src/
    
    zizmor:
      name: Zizmor checks
      runs-on: ubuntu-latest
      permissions:
        security-events: write
        contents: read
        actions: read
      steps:
        - uses: actions/checkout@v6
          with:
            persist-credentials: false
        
        - uses: zizmorcore/zizmor-action@v0.5.6
