name: Remind about changelog & docs on PRs

on:
  pull_request_target:
    branches: [dev]
    types: [opened, reopened]

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Post reminder comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Check if comment already exists to avoid duplicates
            const { data: comments } = await github.rest.issues.listComments({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            const botComment = comments.find(comment => 
              comment.user.type === 'Bot' && 
              comment.body.includes('## Reminder')
            );

            // Only post if we haven't already commented
            if (!botComment) {
              await github.rest.issues.createComment({
                issue_number: context.payload.pull_request.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "## Reminder\n\nPlease remember to update the changelog (in the CHANGELOG.md file) and documentation (over at [VSC-NeuroPilot/docs](https://github.com/VSC-NeuroPilot/docs)) if necessary. Thank you!"
              });
            }
